kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cwave-cluster

nodes:
  - role: control-plane
    image: kindest/node:v1.32.5

  - role: worker
    image: kindest/node:v1.32.5

  - role: worker
    image: kindest/node:v1.32.5
